title: 재야의 숨은 초보
description: 재야의 숨은 고수가 되고 싶은 초심자
author: HiddenBeginner
github: https://github.com/HiddenBeginner
about: 안녕하세요. 방문해 주셔서 감사합니다. 아직 실력이 많이 부족하지만 언젠가 고수 반열에 들어서 이 세상에 많은 기여를 하겠습니다.
avatar_url: /static/img/HDBG.png
timezone: Asia/Seoul

enableTags: true
tagarray: []

enableCat: true
catarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/HiddenBeginner"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/hiddenbeginner"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Publications
      url: /publications/
    - text: Donors
      url: /donors/
    - text: 심층강화학습 책
      url: /Deep-Reinforcement-Learnings/book/intro.html

url: "https://hiddenbeginner.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
gems:
  - jekyll-paginate
  - jekyll-gist

# Conversion 
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
    
google_analytics: 'UA-155743928-2'
