title: 재야의 숨은 초보
description: 재야의 숨은 고수가 되고 싶은 초심자
author: HiddenBeginner (이동진)
github: https://github.com/HiddenBeginner
about: 안녕하세요. 아주대학교에서 수학을 전공하고 있는 이동진입니다. 빅 데이터 분석 및 산업수학 문제 해결에 관심을 가지고 공부하고 있습니다.
avatar_url: /static/img/190524_resize.jpg

enableTags: true
tagarray: []

enableCat: true
catarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/HiddenBeginner"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/

url: "https://hiddenbeginner.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
gems:
  - jekyll-paginate
  - jekyll-gist

# Conversion 
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
